apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: smokaleksander/auth-service
      context: backend/auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/**/*.py"
            dest: .
    - image: smokaleksander/products-service
      context: backend/products-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/**/*.py"
            dest: .
    - image: smokaleksander/nextjs
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: smokaleksander/orders-service
      context: backend/orders-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.py"
            dest: .
